name: Download 3x-ui Release Asset

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download x-ui-linux-amd64.tar.gz
        uses: robinraju/release-downloader@v1
        with:
          repository: MHSanaei/3x-ui
          tag: v2.9.2
          fileName: "x-ui-linux-amd64.tar.gz"
          out-file-path: ./downloads
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add downloads/x-ui-linux-amd64.tar.gz
          git commit -m "Add x-ui-linux-amd64.tar.gz"
          git push
